### ISSUE TITLE
Density interval

### ISSUE THREAD

**Issue by Laurenssiemons** [aoterodelaroza/nciplot#9]
Hello,

I want to visualise interactions within a certain density interval and on the website of NCIPLOT I found a post-processing script (range.csh) to achieve this. I do not have a lot of experience with these kinds of script. I tried to fill in the blanks to achieve the result that I wanted but without succes. I wonder if someone can provide an example on how to visualise interactions within a certain density interval which I can then use on my system under investigation.

Thanks in advance,
Laurens Siemons
UAntwerp

**Comment by aoterodelaroza** [comment]
Hi Laurens: That script is not in this repository, and therefore not maintained by me. I suggest you contact the author. There is cutden.awk in tools/ that does something similar to your description, however.
